NetTeam\DDD\Enum:
    constraints:
        - NetTeam\Bundle\DDDBundle\Validator\Constraints\EnumValue: ~

NetTeam\DDD\ValueObject\Range:
    constraints:
        - NetTeam\Bundle\DDDBundle\Validator\Constraints\RangeLimits: ~

NetTeam\DDD\ValueObject\MoneyRange:
    properties:
        min:
            - Type:
                type: NetTeam\DDD\ValueObject\Money
        max:
            - Type:
                type: NetTeam\DDD\ValueObject\Money

NetTeam\DDD\ValueObject\DateRange:
    properties:
        min:
            - Type:
                type: \DateTime
        max:
            - Type:
                type: \DateTime
