NetTeam\DDD\Enum:
    constraints:
        - NetTeam\Bundle\DDDBundle\Validator\Constraints\EnumValue: ~

NetTeam\DDD\ValueObject\Range:
    constraints:
        - NetTeam\Bundle\DDDBundle\Validator\Constraints\RangeValue: ~
