NetTeam\DDD\Enum:
    constraints:
        - NetTeam\Bundle\DDDBundle\Validator\Constraints\EnumValue: ~

NetTeam\DDD\ValueObject\Range:
    constraints:
        - NetTeam\Bundle\DDDBundle\Validator\Constraints\RangeValue: ~

NetTeam\DDD\ValueObject\MoneyRange:
    constraints:
        - NetTeam\Bundle\DDDBundle\Validator\Constraints\MoneyRangeValue: ~

NetTeam\DDD\ValueObject\DateRange:
    constraints:
        - NetTeam\Bundle\DDDBundle\Validator\Constraints\DateRangeValue: ~
